# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_conf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='client_conf.proto',
  package='tapdance',
  syntax='proto2',
  serialized_pb=_b('\n\x11\x63lient_conf.proto\x12\x08tapdance\"6\n\x06PubKey\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\x1f\n\x04type\x18\x02 \x01(\x0e\x32\x11.tapdance.KeyType\"u\n\x0cTLSDecoySpec\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x10\n\x08ipv4addr\x18\x02 \x01(\x07\x12 \n\x06pubkey\x18\x03 \x01(\x0b\x32\x10.tapdance.PubKey\x12\x0f\n\x07timeout\x18\x04 \x01(\r\x12\x0e\n\x06tcpwin\x18\x05 \x01(\r\"s\n\nClientConf\x12\'\n\ndecoy_list\x18\x01 \x01(\x0b\x32\x13.tapdance.DecoyList\x12\x12\n\ngeneration\x18\x02 \x01(\r\x12(\n\x0e\x64\x65\x66\x61ult_pubkey\x18\x03 \x01(\x0b\x32\x10.tapdance.PubKey\"7\n\tDecoyList\x12*\n\ntls_decoys\x18\x01 \x03(\x0b\x32\x16.tapdance.TLSDecoySpec\"\x9b\x01\n\x0fStationToClient\x12\x18\n\x10protocol_version\x18\x01 \x01(\r\x12\x32\n\x10state_transition\x18\x02 \x01(\x0e\x32\x18.tapdance.S2C_Transition\x12)\n\x0b\x63onfig_info\x18\x03 \x01(\x0b\x32\x14.tapdance.ClientConf\x12\x0f\n\x07padding\x18\x64 \x01(\x0c\"\x8f\x01\n\x0f\x43lientToStation\x12\x18\n\x10protocol_version\x18\x01 \x01(\r\x12\x1d\n\x15\x64\x65\x63oy_list_generation\x18\x02 \x01(\r\x12\x32\n\x10state_transition\x18\x03 \x01(\x0e\x32\x18.tapdance.C2S_Transition\x12\x0f\n\x07padding\x18\x64 \x01(\x0c*+\n\x07KeyType\x12\x0f\n\x0b\x41\x45S_GCM_128\x10Z\x12\x0f\n\x0b\x41\x45S_GCM_256\x10[*d\n\x0e\x43\x32S_Transition\x12\x11\n\rC2S_NO_CHANGE\x10\x00\x12\x18\n\x14\x43\x32S_EXPECT_RECONNECT\x10\x02\x12\x15\n\x11\x43\x32S_SESSION_CLOSE\x10\x03\x12\x0e\n\tC2S_ERROR\x10\xff\x01*{\n\x0eS2C_Transition\x12\x11\n\rS2C_NO_CHANGE\x10\x00\x12\x14\n\x10S2C_SESSION_INIT\x10\x01\x12\x19\n\x15S2C_CONFIRM_RECONNECT\x10\x02\x12\x15\n\x11S2C_SESSION_CLOSE\x10\x03\x12\x0e\n\tS2C_ERROR\x10\xff\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_KEYTYPE = _descriptor.EnumDescriptor(
  name='KeyType',
  full_name='tapdance.KeyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AES_GCM_128', index=0, number=90,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AES_GCM_256', index=1, number=91,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=684,
  serialized_end=727,
)
_sym_db.RegisterEnumDescriptor(_KEYTYPE)

KeyType = enum_type_wrapper.EnumTypeWrapper(_KEYTYPE)
_C2S_TRANSITION = _descriptor.EnumDescriptor(
  name='C2S_Transition',
  full_name='tapdance.C2S_Transition',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='C2S_NO_CHANGE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C2S_EXPECT_RECONNECT', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C2S_SESSION_CLOSE', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C2S_ERROR', index=3, number=255,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=729,
  serialized_end=829,
)
_sym_db.RegisterEnumDescriptor(_C2S_TRANSITION)

C2S_Transition = enum_type_wrapper.EnumTypeWrapper(_C2S_TRANSITION)
_S2C_TRANSITION = _descriptor.EnumDescriptor(
  name='S2C_Transition',
  full_name='tapdance.S2C_Transition',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='S2C_NO_CHANGE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S2C_SESSION_INIT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S2C_CONFIRM_RECONNECT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S2C_SESSION_CLOSE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S2C_ERROR', index=4, number=255,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=831,
  serialized_end=954,
)
_sym_db.RegisterEnumDescriptor(_S2C_TRANSITION)

S2C_Transition = enum_type_wrapper.EnumTypeWrapper(_S2C_TRANSITION)
AES_GCM_128 = 90
AES_GCM_256 = 91
C2S_NO_CHANGE = 0
C2S_EXPECT_RECONNECT = 2
C2S_SESSION_CLOSE = 3
C2S_ERROR = 255
S2C_NO_CHANGE = 0
S2C_SESSION_INIT = 1
S2C_CONFIRM_RECONNECT = 2
S2C_SESSION_CLOSE = 3
S2C_ERROR = 255



_PUBKEY = _descriptor.Descriptor(
  name='PubKey',
  full_name='tapdance.PubKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tapdance.PubKey.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='tapdance.PubKey.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=90,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=85,
)


_TLSDECOYSPEC = _descriptor.Descriptor(
  name='TLSDecoySpec',
  full_name='tapdance.TLSDecoySpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='tapdance.TLSDecoySpec.hostname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ipv4addr', full_name='tapdance.TLSDecoySpec.ipv4addr', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pubkey', full_name='tapdance.TLSDecoySpec.pubkey', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='tapdance.TLSDecoySpec.timeout', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tcpwin', full_name='tapdance.TLSDecoySpec.tcpwin', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=204,
)


_CLIENTCONF = _descriptor.Descriptor(
  name='ClientConf',
  full_name='tapdance.ClientConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='decoy_list', full_name='tapdance.ClientConf.decoy_list', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='generation', full_name='tapdance.ClientConf.generation', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='default_pubkey', full_name='tapdance.ClientConf.default_pubkey', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=321,
)


_DECOYLIST = _descriptor.Descriptor(
  name='DecoyList',
  full_name='tapdance.DecoyList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tls_decoys', full_name='tapdance.DecoyList.tls_decoys', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=378,
)


_STATIONTOCLIENT = _descriptor.Descriptor(
  name='StationToClient',
  full_name='tapdance.StationToClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protocol_version', full_name='tapdance.StationToClient.protocol_version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state_transition', full_name='tapdance.StationToClient.state_transition', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='config_info', full_name='tapdance.StationToClient.config_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='padding', full_name='tapdance.StationToClient.padding', index=3,
      number=100, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=536,
)


_CLIENTTOSTATION = _descriptor.Descriptor(
  name='ClientToStation',
  full_name='tapdance.ClientToStation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protocol_version', full_name='tapdance.ClientToStation.protocol_version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='decoy_list_generation', full_name='tapdance.ClientToStation.decoy_list_generation', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state_transition', full_name='tapdance.ClientToStation.state_transition', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='padding', full_name='tapdance.ClientToStation.padding', index=3,
      number=100, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=539,
  serialized_end=682,
)

_PUBKEY.fields_by_name['type'].enum_type = _KEYTYPE
_TLSDECOYSPEC.fields_by_name['pubkey'].message_type = _PUBKEY
_CLIENTCONF.fields_by_name['decoy_list'].message_type = _DECOYLIST
_CLIENTCONF.fields_by_name['default_pubkey'].message_type = _PUBKEY
_DECOYLIST.fields_by_name['tls_decoys'].message_type = _TLSDECOYSPEC
_STATIONTOCLIENT.fields_by_name['state_transition'].enum_type = _S2C_TRANSITION
_STATIONTOCLIENT.fields_by_name['config_info'].message_type = _CLIENTCONF
_CLIENTTOSTATION.fields_by_name['state_transition'].enum_type = _C2S_TRANSITION
DESCRIPTOR.message_types_by_name['PubKey'] = _PUBKEY
DESCRIPTOR.message_types_by_name['TLSDecoySpec'] = _TLSDECOYSPEC
DESCRIPTOR.message_types_by_name['ClientConf'] = _CLIENTCONF
DESCRIPTOR.message_types_by_name['DecoyList'] = _DECOYLIST
DESCRIPTOR.message_types_by_name['StationToClient'] = _STATIONTOCLIENT
DESCRIPTOR.message_types_by_name['ClientToStation'] = _CLIENTTOSTATION
DESCRIPTOR.enum_types_by_name['KeyType'] = _KEYTYPE
DESCRIPTOR.enum_types_by_name['C2S_Transition'] = _C2S_TRANSITION
DESCRIPTOR.enum_types_by_name['S2C_Transition'] = _S2C_TRANSITION

PubKey = _reflection.GeneratedProtocolMessageType('PubKey', (_message.Message,), dict(
  DESCRIPTOR = _PUBKEY,
  __module__ = 'client_conf_pb2'
  # @@protoc_insertion_point(class_scope:tapdance.PubKey)
  ))
_sym_db.RegisterMessage(PubKey)

TLSDecoySpec = _reflection.GeneratedProtocolMessageType('TLSDecoySpec', (_message.Message,), dict(
  DESCRIPTOR = _TLSDECOYSPEC,
  __module__ = 'client_conf_pb2'
  # @@protoc_insertion_point(class_scope:tapdance.TLSDecoySpec)
  ))
_sym_db.RegisterMessage(TLSDecoySpec)

ClientConf = _reflection.GeneratedProtocolMessageType('ClientConf', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTCONF,
  __module__ = 'client_conf_pb2'
  # @@protoc_insertion_point(class_scope:tapdance.ClientConf)
  ))
_sym_db.RegisterMessage(ClientConf)

DecoyList = _reflection.GeneratedProtocolMessageType('DecoyList', (_message.Message,), dict(
  DESCRIPTOR = _DECOYLIST,
  __module__ = 'client_conf_pb2'
  # @@protoc_insertion_point(class_scope:tapdance.DecoyList)
  ))
_sym_db.RegisterMessage(DecoyList)

StationToClient = _reflection.GeneratedProtocolMessageType('StationToClient', (_message.Message,), dict(
  DESCRIPTOR = _STATIONTOCLIENT,
  __module__ = 'client_conf_pb2'
  # @@protoc_insertion_point(class_scope:tapdance.StationToClient)
  ))
_sym_db.RegisterMessage(StationToClient)

ClientToStation = _reflection.GeneratedProtocolMessageType('ClientToStation', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTTOSTATION,
  __module__ = 'client_conf_pb2'
  # @@protoc_insertion_point(class_scope:tapdance.ClientToStation)
  ))
_sym_db.RegisterMessage(ClientToStation)


# @@protoc_insertion_point(module_scope)
